- experiment_name: "ippo_test1"
  experiment: 
    #seed: 100
    checkpoint_freq: 20
    start_from_checkpoint: False
    log_save_freq: 10
  environment:
    type: "PGMA"
    horizon: 1000
    num_agents: 1
    normalize_reward: True
    num_env_runners: 2
    allow_respawn: False
    traffic_density: 0
    # Estas son necesarias para el random
    start_seed: 9
    num_scenarios: 1000
    map: 8
  agent:
    algorithm: "IPPO"
    observation: "Lidar"
    policy_type: "MLP"
  hyperparameters:
    learning_rate: 0.001
    n_epochs: 1000
    gamma: 0.995
    clip_param: 0.2
    lambda: 0.95
    entropy_coeff: [[0, 0.001], [2000000, 0.0001]]
    rollout_fragment_length: 256
    minibatch_size: 512
    train_batch_size: 4096
    vf_clip_param: 100.0 # Basicamente no clipping
    grad_clip: 0.5
