- experiment_name: "ippo_test1"
  experiment: 
    seed: 42
    checkpoint_freq: 20
    start_from_checkpoint: False
    log_save_freq: 10
  environment:
    type: "Roundabout"
    horizon: 1000
    num_agents: 10
    num_env_runners: 2
    allow_respawn: False
    traffic_density: 0
  agent:
    algorithm: "IPPO"
    observation: "Lidar"
    policy_type: "MLP"
  hyperparameters:
    learning_rate: [[0, 0.0001], [800000, 0.00005], [4000000, 0.00001]]
    n_epochs: 1000
    gamma: 0.995
    clip_param: 0.2
    lambda: 0.95
    entropy_coeff: [[0, 0.005], [800000, 0.003], [4000000, 0.001]]
    rollout_fragment_length: 256
    minibatch_size: 512
    train_batch_size: 4096
    vf_clip_param: 10.0
    grad_clip: 0.5
