experiment_name: "ippo_test"

experiment:
  seed: 42
  checkpoint_freq: 50

environment:
  horizon: 1000
  num_agents: 3
  num_env_runners: 2
  allow_respawn: False

agent:
  algorithm: "PPO"
  policy_type: "MlpPolicy"

hyperparameters:
  learning_rate: 0.001
  # train_batch_size_per_learner: 64
  n_epochs: 1000
  gamma: 0.995
  clip_param: 0.2
